spring.application.name=ApiGateway

server.port=5000

# Gateway Auto-Routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka Client configs
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=account-microservice
spring.cloud.gateway.routes[0].uri=lb://ACCOUNT-MICROSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/ACCOUNT-MICROSERVICE/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1